* mirrorselect: fixed debian mirror discovering. * mirrorselect: added -u switch which skips the execution of update.

diff --git a/mirrorselect b/mirrorselect
--- a/mirrorselect
+++ b/mirrorselect
@@ -31,7 +31,7 @@ error() {
 
 
 help() {
-	echo "$0 <option>- Checks which mirror is the fastest."
+	echo "$0 <option> - Checks which mirror is the fastest."
 	echo ""
 	echo "Available arguments:"
 	echo "   -s <set>       - 'debian' or 'semplice' (default: 'semplice')"
@@ -39,6 +39,7 @@ help() {
 	echo "   -o             - Enable sources (disabled by default)"
 	echo "   -f             - Use FTP protocol if available."
 	echo "   -n             - Non-interactive."
+	echo "   -u             - Do not update database after mirror selection."
 	echo "   -h|--help      - This message"
 	echo "   -v             - Displays the version."
 	echo -e "\nBugs to: launchpad.net/semplice-utilities"
@@ -56,7 +57,7 @@ semplice_parse() {
 debian_parse() {
 	wget ftp://ftp.debian.org/debian/README.mirrors.html -O /tmp/.debian-mirrors.html || error "Unable to download the mirrors file."
 	
-	list="`grep '<a href=' /tmp/.debian-mirrors.html | grep '<td' | cut -d '>' -f2 | cut -d '\"' -f2 | grep $PROTO`"
+	list="`grep '<a rel=\"nofollow\" href=' /tmp/.debian-mirrors.html | grep '<td' | cut -d '>' -f2 | cut -d '\"' -f4 | grep $PROTO`"
 	sources="$debian_sources"
 }
 
@@ -87,7 +88,7 @@ do_test() {
 	result="`echo $res | awk '{ print $2 }'`"
 	
 	echo "This is the fastest mirror: $result"
-	echo "Re-generating $sources..." # Must add support for debian too!
+	echo "Re-generating $sources..."
 	cat > $sources <<EOF
 # $sources, generated by mirrorselect $VERSION
 deb $result $DISTRO main contrib non-free
@@ -103,9 +104,8 @@ EOF
 EOF
 	fi
 	echo "Generation done. Refreshing pacakge database..."
-	apt-get update
-	if [ "$?" != "0" ]; then
-		error "apt-get update encountred an error."
+	if [ -z "$NOUPDATE" ]; then
+		apt-get update || error "apt-get update encountred an error."
 	fi
 	echo "Done. Enjoy your new mirror!"
 }
@@ -124,6 +124,9 @@ parseargs() {
 			-n)
 				shift
 				INTERACTIVE="n";;
+			-u)
+				shift
+				NOUPDATE="y";;
 			-f)
 				shift
 				PROTO="ftp://";;
