* Initial pulse release. * mirrorselect: new release 1.0. Supports debian set,   deb-srcs, set releases. * semplice.list: updated to work with mirrorselect 1.0.

diff --git a/mirrorselect b/mirrorselect
--- a/mirrorselect
+++ b/mirrorselect
@@ -2,16 +2,22 @@
 
 #
 # mirrorselect: select the fastest mirror from a list!
-# Copyright (C) 2010 Semplice Team. All rights reserved.
+# Copyright (C) 2010-12 Semplice Team. All rights reserved.
 # This script is released under the terms of the GNU GPL license, version 3 or later.
 #
 
 semplice_list="/usr/share/semplice-utilities/mirrorselect/semplice.list"
 semplice_sources="/etc/apt/sources.list.d/semplice.list"
 
-VERSION="0.1"
+debian_sources="/etc/apt/sources.list"
+
+VERSION="1.0"
 INTERACTIVE="y"
 SET="semplice"
+SRC_ENABLE=""
+
+SEMPLICE_DISTRO="pulse"
+DEBIAN_DISTRO="unstable"
 
 error() {
   echo -e "\033[1;31m$1\033[m" >&2
@@ -27,28 +33,37 @@ help() {
 	echo "$0 <option>- Checks which mirror is the fastest."
 	echo ""
 	echo "Available arguments:"
-	echo "	-s <set>	- Currently only 'semplice', which is the default."
-	echo "	-n			- Non-interactive."
-	echo "  -h|--help	- This message"
-	echo "	-v			- Displays the version."
+	echo "   -s <set>	- Currently only 'semplice', which is the default."
+	echo "   -d <distro>	- Distribution to use (default is 'pulse' for semplice, 'unstable' for debian)"
+	echo "   -o		- Enable sources (disabled by default)"
+	echo "   -n		- Non-interactive."
+	echo "   -h|--help	- This message"
+	echo "   -v		- Displays the version."
 	echo -e "\nBugs to: launchpad.net/semplice"
 }
 
 semplice_parse() {
 	# The mirrors are written in a local file. No need to parse it.
 	if [ ! -e "$semplice_list" ]; then
-		error "The mirror list ($semplice_list) doesn't exists. Aborting."
+		error "The mirror list ($semplice_list) doesn't exist. Aborting."
 	fi
 	list="`cat $semplice_list`"
 	sources="$semplice_sources"
 }
 
-do_test() {
-	if [ ! -e "$sources" ]; then
-		error "The sources file ($sources) doesn't exist. Aborting."
-	fi
+debian_parse() {
+	wget ftp://ftp.debian.org/debian/README.mirrors.html -O /tmp/.debian-mirrors.html || error "Unable to download the mirrors file."
 	
-	if [ "$INTERACTIVE" ]; then
+	list="`grep '<a href=' /tmp/.debian-mirrors.html | grep '<td' | cut -d '>' -f2 | cut -d '\"' -f2`"
+	sources="$debian_sources"
+}
+
+do_test() {
+	#if [ ! -e "$sources" ]; then
+	#	error "The sources file ($sources) doesn't exist. Aborting."
+	#fi
+	
+	if [ "$INTERACTIVE" = "y" ]; then
 		read -p "This will overwrite $sources. You really want to continue? [y/n]: " scelta
 		if [ "$scelta" = "n" ]; then
 			exit 0
@@ -72,9 +87,19 @@ do_test() {
 	echo "This is the fastest mirror: $result"
 	echo "Re-generating $sources..." # Must add support for debian too!
 	cat > $sources <<EOF
-# Semplice Linux archive mirror list, generated by mirrorselect $VERSION
-deb $result/project/semplice-linux/repo rocks main
+# $sources, generated by mirrorselect $VERSION
+deb $result $DISTRO main contrib non-free
 EOF
+	# Should enable deb-src?
+	if [ "$SRC_ENABLE" ]; then
+		cat >> $sources <<EOF
+deb-src $result $DISTRO main contrib non-free
+EOF
+	else
+		cat >> $sources <<EOF
+#deb-src $result $DISTRO main contrib non-free
+EOF
+	fi
 	echo "Generation done. Refreshing pacakge database..."
 	apt-get update
 	if [ "$?" != "0" ]; then
@@ -90,9 +115,16 @@ parseargs() {
 				shift
 				SET="$1"
 				shift;;
+			-d)
+				shift
+				DISTRO="$1"
+				shift;;
 			-n)
 				shift
 				INTERACTIVE="n";;
+			-o)
+				shift
+				SRC_ENABLE="True";;
 			-h|--help)
 				help
 				exit 0;;
@@ -113,6 +145,8 @@ parseargs() {
 }
 
 parseargs "$@"
+[ -z "$DISTRO" ] && [ "$SET" = "semplice" ] && DISTRO=$SEMPLICE_DISTRO
+[ -z "$DISTRO" ] && [ "$SET" = "debian" ] && DISTRO=$DEBIAN_DISTRO
 
 if [ "$USER" != "root" ]; then
 	error "You must be root to use mirrorselect."
@@ -121,6 +155,8 @@ fi
 # Begin...
 if [ "$SET" = "semplice" ]; then
 	semplice_parse
+elif [ "$SET" = "debian" ]; then
+	debian_parse
 else
 	error "Set $SET not supported. Aborting."
 fi
